# netlify.toml

# netlify.toml

[build]
  command = "npm run build"
  publish = "frontend/dist"

[[redirects]]
  from = "/api/*"
  to = "https://yourprint.netlify.app/:splat"
  status = 200


[build.environment]
  FIREBASE_API_KEY = "AIzaSyBx5m_a_VToA564dZBn_mjymX-HCBT0uCo"
  FIREBASE_AUTH_DOMAIN = "yourprint-fe255.firebaseapp.com"
  FIREBASE_PROJECT_ID = "yourprint-fe255"
  FIREBASE_STORAGE_BUCKET = "yourprint-fe255.appspot.com"
  FIREBASE_MESSAGING_SENDER_ID = "234659911880"
  FIREBASE_APP_ID = "1:234659911880:web:d88160962efbd4fd566dfd"
  FIREBASE_MEASUREMENT_ID = "G-MWZ4LG1T5N"
  VITE_FIREBASE_API_KEY = "AIzaSyBx5m_a_VToA564dZBn_mjymX-HCBT0uCo"
  VITE_FIREBASE_AUTH_DOMAIN = "yourprint-fe255.firebaseapp.com"
  VITE_FIREBASE_PROJECT_ID = "yourprint-fe255"
  VITE_FIREBASE_STORAGE_BUCKET = "yourprint-fe255.appspot.com"
  VITE_FIREBASE_MESSAGING_SENDER_ID = "234659911880"
  VITE_FIREBASE_APP_ID = "1:234659911880:web:d88160962efbd4fd566dfd"
  VITE_FIREBASE_MEASUREMENT_ID = "G-MWZ4LG1T5N"
