# netlify.toml

[build]
  command = "npm run build" 
  publish = "frontend/dist" 

[build.functions]
  command = "npm run build" 
  publish = "backend/build"

[build.environment]

[FIREBASE_API_KEY]
  value = "AIzaSyBx5m_a_VToA564dZBn_mjymX-HCBT0uCo"
[FIREBASE_AUTH_DOMAIN]
  value = "yourprint-fe255.firebaseapp.com"
[FIREBASE_PROJECT_ID]
  value = "yourprint-fe255"
[FIREBASE_STORAGE_BUCKET]
  value = "yourprint-fe255.appspot.com"
[FIREBASE_MESSAGING_SENDER_ID]
  value = "234659911880"
[FIREBASE_APP_ID]
  value = "1:234659911880:web:d88160962efbd4fd566dfd"
[FIREBASE_MEASUREMENT_ID]
  value = "G-MWZ4LG1T5N"
